# Generated by Django 3.1.5 on 2021-06-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=60)),
                ('phone', models.IntegerField(max_length=13)),
                ('gender', models.CharField(max_length=8)),
                ('qualification', models.CharField(max_length=20)),
                ('occupation', models.CharField(max_length=20)),
            ],
        ),
    ]
